[package]
name = "parse_sbus"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A crate to parse SBUS packets to data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
